# Site settings
title: Dr. S. Ahmad's Blog
description: "A personal blog of Dr. Md. Saju Ahmad for sharing Homeopathic principles."
url: "https://blog.jannathomeo.org"
author:
  name: "Dr. Md. Saju Ahmad"
  email: "info.rahiq@gmail.com"
  url: "https://www.jannathomeo.org"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

plugins:
- jekyll-seo-tag

# Plugins
gems:
  - jekyll-paginate
gems:
  - jekyll-sitemap

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
